"""add llm_calls error column

Revision ID: 3e773e937d72
Revises: bdeed15bc1b9
Create Date: 2026-07-29 09:00:13.145559
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '3e773e937d72'
down_revision: str | None = 'bdeed15bc1b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_calls', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_calls', 'error')
    # ### end Alembic commands ###
