"""initial schema

Revision ID: fc19859676fa
Revises: 
Create Date: 2026-07-28 23:55:37.353846
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'fc19859676fa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # entities.embedding is a pgvector column; the extension must exist first.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', name='userrole', native_enum=False), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('POSTGRES', 'MYSQL', 'MSSQL', 'ORACLE', 'REST', 'MCP', name='sourcekind', native_enum=False), nullable=False),
    sa.Column('config_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('sampling_policy', sa.Enum('MASKED', 'SCHEMA_ONLY', name='samplingpolicy', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCANNING', 'READY', 'ERROR', name='sourcestatus', native_enum=False), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('entities',
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('schema_name', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('structural', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structural_hash', sa.String(length=64), nullable=False),
    sa.Column('description_ai', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description_human', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'STALE', 'IGNORED', 'ARCHIVED', 'DESCRIBE_FAILED', name='entitystatus', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('row_count_approx', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'schema_name', 'name', name='uq_entity_identity')
    )
    op.create_index(op.f('ix_entities_data_source_id'), 'entities', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_entities_status'), 'entities', ['status'], unique=False)
    op.create_table('scans',
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'PARTIAL', 'FAILED', name='scanstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('structural_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_data_source_id'), 'scans', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('fields',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('is_pk', sa.Boolean(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meaning_ai', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meaning_human', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enum_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('pii_class', sa.Enum('NONE', 'LOW', 'HIGH', name='piiclass', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_entity_id'), 'fields', ['entity_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_purpose'), 'llm_calls', ['purpose'], unique=False)
    op.create_index(op.f('ix_llm_calls_scan_id'), 'llm_calls', ['scan_id'], unique=False)
    op.create_table('relationships',
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('from_field', sa.String(length=200), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_field', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('DECLARED', 'INFERRED', name='relationshipkind', native_enum=False), nullable=False),
    sa.Column('cardinality', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='relationshipstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_data_source_id'), 'relationships', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_relationships_from_entity_id'), 'relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_to_entity_id'), 'relationships', ['to_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_to_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_data_source_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_llm_calls_scan_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_purpose'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_fields_entity_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_data_source_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_entities_status'), table_name='entities')
    op.drop_index(op.f('ix_entities_data_source_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_table('settings')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
